name: MachinaEconomy
version: 1.0
main: org.MachinaEconomy.ThePrometeus.Main
author: ThePrometeus
depend: [Vault]

commands:
    money:
        description: MachinaEconomy command.
        usage: /money [argument]